### ISSUE TITLE
Why was mod menu integration removed and what is the alternative?

### ISSUE THREAD

**Issue by ghost** [Lortseam/completeconfig#16]
Some more documentation on this would be helpful

**Comment by Lortseam** [comment]
Mod Menu changed the way how provided config screens are loaded, hence CompleteConfig cannot provide the config screens anymore.

You can still register your config screen yourself though (see https://github.com/TerraformersMC/ModMenu/wiki/API#java-api). I've added an [example](https://github.com/Lortseam/completeconfig/wiki/Screen-Builder#mod-menu) to the wiki.
