### ISSUE TITLE
no 2.5.2

### ISSUE THREAD

**Issue by zc1108aaa** [Lortseam/completeconfig#28]
![image](https://github.com/Lortseam/completeconfig/assets/155424398/2df28b9b-a6d5-42e4-be09-96944d2c1b7b)
0
![image](https://github.com/Lortseam/completeconfig/assets/155424398/7c0392bb-d525-4bcc-8fed-585dfd64baaf)

**Comment by Lortseam** [comment]
If you remove the filter, you will see version 2.5.2.
