### ISSUE TITLE
Update Coat to its 1.19.3 version

### ISSUE THREAD

**Issue by Siphalor** [Lortseam/completeconfig#4]
Hi,

Coat requires an update for 1.19.3, otherwise the game is gonna crash when opening the config screen.
Version `1.0.0-beta.19+mc1.19.3` is currently the latest version for 1.19.3 (gotta love my beta strategy :P).

Originally reported on Mouse Wheelie as a compatibility issue: https://github.com/Siphalor/mouse-wheelie/issues/198

Also, since you seem to be one of the few people, apart from myself, that actually use Coat, I'd love to hear some feedback :)

**Comment by Lortseam** [comment]
> Also, since you seem to be one of the few people, apart from myself, that actually use Coat, I'd love to hear some feedback :)

I'm not really using Coat apart from this library, but I think it's great to have some different options to create config screens.
